services:

  # =========================
  # PYTHON SEM REDIS
  # =========================
  web-py-sem-redis:
    image: php:7-apache
    ports:
      - "8080:80"
    environment:
      - API_ENDPOINT=http://api-py-sem-redis:5000/api/
    volumes:
      - ./link-extractor/linkextractor-step4/www:/var/www/html

  api-py-sem-redis:
    image: linkextractor-api:step4-python
    build: ./link-extractor/linkextractor-step4/api
    ports:
      - "5000:5000"

  # =========================
  # PYTHON COM REDIS
  # =========================
  web-py-redis:
    image: linkextractor-web:step5-php
    build: ./link-extractor/linkextractor-step5/www
    ports:
      - "8081:80"
    environment:
      - API_ENDPOINT=http://api-py-redis:5000/api/

  api-py-redis:
    image: linkextractor-api:step5-python
    build: ./link-extractor/linkextractor-step5/api
    ports:
      - "5001:5000"
    environment:
      - REDIS_URL=redis://redis-py:6379
  redis-py:
    image: redis

  # =========================
  # RUBY SEM REDIS
  # =========================
  web-ruby-sem-redis:
    image: linkextractor-web:step6-php
    build: ./link-extractor/linkextractor-step7/www
    ports:
      - "8082:80"
    environment:
      - API_ENDPOINT=http://api-ruby-sem-redis:4567/api/

  api-ruby-sem-redis:
    image: linkextractor-api:step7-ruby
    build: ./link-extractor/linkextractor-step7/api
    ports:
      - "4567:4567"
    volumes:
      - ./logs:/app/logs

  # =========================
  # RUBY COM REDIS
  # =========================
  web-ruby-redis:
    image: linkextractor-web:step6-php
    build: ./link-extractor/linkextractor-step6/www
    ports:
      - "8083:80"
    environment:
      - API_ENDPOINT=http://api-ruby-redis:4567/api/

  api-ruby-redis:
    image: linkextractor-api:step6-ruby
    build: ./link-extractor/linkextractor-step6/api
    ports:
      - "4568:4567"
    environment:
      - REDIS_URL=redis://redis-ruby:6379
    volumes:
      - ./logs:/app/logs

  redis-ruby:
    image: redis

  # =========================
  # LOCUST
  # =========================
  locust:
    image: locustio/locust
    container_name: locust
    ports:
      - "8084:80"
    volumes:
      - ./locust:/mnt/locust
      - ./data:/mnt/data
    working_dir: /mnt/locust
    # command: -f teste-carga.py --host=http://web-py-redis