services:
  nginx:
    image: nginx:1.19.0
    container_name: nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3
    networks:
      - wp_network

  wordpress1:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress1
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
    networks:
      - wp_network

  wordpress2:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress2
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
    networks:
      - wp_network

  wordpress3:
    image: wordpress:5.4.2-php7.2-apache
    container_name: wordpress3
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: wordpressdb
      WORDPRESS_DB_USER: wpuser
      WORDPRESS_DB_PASSWORD: wppassword
    volumes:
      - ./html:/var/www/html
    depends_on:
      - mysql
    networks:
      - wp_network

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: wpuser
      MYSQL_PASSWORD: wppassword
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - wp_network

  locust:
    image: locustio/locust
    container_name: locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
      - ./data:/mnt/data
    working_dir: /mnt/locust
    command: -f teste-carga.py --host=http://nginx
    depends_on:
      - nginx
    networks:
      - wp_network

volumes:
  mysql_data:

networks:
  wp_network:
    driver: bridge