spring.application.name=java.grpc
server.port=9090

spring.datasource.url=jdbc:h2:mem:musicasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=banco
spring.datasource.password=senha

spring.jpa.hibernate.ddl-auto=create-drop

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console