# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: musica.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'musica.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cmusica.proto\"\x15\n\x13TodasMusicasRequest\";\n\x0eMusicaResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\x0f\n\x07\x61rtista\x18\x03 \x01(\t\"8\n\x14TodasMusicasResponse\x12 \n\x07musicas\x18\x01 \x03(\x0b\x32\x0f.MusicaResponse2N\n\rMusicaService\x12=\n\x0eTodasAsMusicas\x12\x14.TodasMusicasRequest\x1a\x15.TodasMusicasResponseB*\n\x19servico.kotlin.grpc.protoB\x0bMusicaProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'musica_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031servico.kotlin.grpc.protoB\013MusicaProtoP\001'
  _globals['_TODASMUSICASREQUEST']._serialized_start=16
  _globals['_TODASMUSICASREQUEST']._serialized_end=37
  _globals['_MUSICARESPONSE']._serialized_start=39
  _globals['_MUSICARESPONSE']._serialized_end=98
  _globals['_TODASMUSICASRESPONSE']._serialized_start=100
  _globals['_TODASMUSICASRESPONSE']._serialized_end=156
  _globals['_MUSICASERVICE']._serialized_start=158
  _globals['_MUSICASERVICE']._serialized_end=236
# @@protoc_insertion_point(module_scope)
