# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: usuario.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'usuario.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rusuario.proto\"\x10\n\x0eUsuarioRequest\":\n\x0fUsuarioResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04nome\x18\x02 \x01(\t\x12\r\n\x05idade\x18\x03 \x01(\x05\"9\n\x13UsuarioListResponse\x12\"\n\x08usuarios\x18\x01 \x03(\x0b\x32\x10.UsuarioResponse2H\n\x0eUsuarioService\x12\x36\n\rTodosUsuarios\x12\x0f.UsuarioRequest\x1a\x14.UsuarioListResponseB+\n\x19servico.kotlin.grpc.protoB\x0cUsuarioProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'usuario_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\031servico.kotlin.grpc.protoB\014UsuarioProtoP\001'
  _globals['_USUARIOREQUEST']._serialized_start=17
  _globals['_USUARIOREQUEST']._serialized_end=33
  _globals['_USUARIORESPONSE']._serialized_start=35
  _globals['_USUARIORESPONSE']._serialized_end=93
  _globals['_USUARIOLISTRESPONSE']._serialized_start=95
  _globals['_USUARIOLISTRESPONSE']._serialized_end=152
  _globals['_USUARIOSERVICE']._serialized_start=154
  _globals['_USUARIOSERVICE']._serialized_end=226
# @@protoc_insertion_point(module_scope)
