<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://soap.java.servico/musica"
           xmlns:tns="http://soap.java.servico/musica"
           elementFormDefault="qualified">

    <xs:element name="getTodasMusicasRequest">
        <xs:complexType>
            <xs:sequence/>
        </xs:complexType>
    </xs:element>

    <xs:element name="getTodasMusicasResponse">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="musica" type="tns:musica" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="musica">
        <xs:sequence>
            <xs:element name="id" type="xs:long"/>
            <xs:element name="nome" type="xs:string"/>
            <xs:element name="artista" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>