events {
    worker_connections 1024;
}

http {

    upstream wordpress {
        server wordpress1;
        server wordpress2;
        server wordpress3;
        # server wordpress4;
        # server wordpress5;
    }

    server {
        listen 80 default_server;
        listen [::]:80 default_server;

        location / {
            add_header X-Upstream $upstream_addr;

            proxy_set_header Host $http_host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_pass http://wordpress;
        }
    }
}