# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: playlist.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'playlist.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplaylist.proto\".\n\x19PlaylistPorUsuarioRequest\x12\x11\n\tidUsuario\x18\x01 \x01(\x03\",\n\x18PlaylistPorMusicaRequest\x12\x10\n\x08idMusica\x18\x01 \x01(\x03\",\n\x10PlaylistResponse\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04nome\x18\x02 \x01(\t\"<\n\x14PlaylistListResponse\x12$\n\tplaylists\x18\x01 \x03(\x0b\x32\x11.PlaylistResponse2\xa3\x01\n\x0fPlaylistService\x12H\n\x13PlaylistsPorUsuario\x12\x1a.PlaylistPorUsuarioRequest\x1a\x15.PlaylistListResponse\x12\x46\n\x12PlaylistsPorMusica\x12\x19.PlaylistPorMusicaRequest\x1a\x15.PlaylistListResponseB*\n\x17servico.java.grpc.protoB\rPlaylistProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'playlist_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\027servico.java.grpc.protoB\rPlaylistProtoP\001'
  _globals['_PLAYLISTPORUSUARIOREQUEST']._serialized_start=18
  _globals['_PLAYLISTPORUSUARIOREQUEST']._serialized_end=64
  _globals['_PLAYLISTPORMUSICAREQUEST']._serialized_start=66
  _globals['_PLAYLISTPORMUSICAREQUEST']._serialized_end=110
  _globals['_PLAYLISTRESPONSE']._serialized_start=112
  _globals['_PLAYLISTRESPONSE']._serialized_end=156
  _globals['_PLAYLISTLISTRESPONSE']._serialized_start=158
  _globals['_PLAYLISTLISTRESPONSE']._serialized_end=218
  _globals['_PLAYLISTSERVICE']._serialized_start=221
  _globals['_PLAYLISTSERVICE']._serialized_end=384
# @@protoc_insertion_point(module_scope)
